# ansible pull
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
    - include_tasks: playbooks/local/ansible.yml
#    - include_tasks: playbooks/local/bmorgan.yml
    - include_tasks: playbooks/local/itst.yml
    - include_tasks: playbooks/local/systemd.yml
    - include_tasks: playbooks/local/packages.yml
    - include_tasks: playbooks/local/sshd.yml
#    - include_tasks: playbooks/local/update_pass.yml
