---
- name: set a cron job
  hosts: 
  become: yes
  gather_facts: no
  tasks:

    - name: Ensure itst user exists
      user:
        name: itst
        state: present

    - name: move the script we want to run
      copy:
        src: playbooks/files/itst/sbin/disk_alert.sh
        dest: /home/itst/sbin/
        owner: itst
        group: itst
        mode: 0755

    - name: set cron job
      cron:
        name: set disk check cron
        user: itst
        minute: "*/10"
        job: /home/itst/sbin/disk_alert.sh

