---
- name: Download and Install all dist updates and reboot if needed
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    # Debian/Ubuntu Updates
    - name: Update packages on Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required on Debian/Ubuntu
      stat:
        path: /var/run/reboot-required
      register: debian_reboot_required
      when: ansible_os_family == "Debian"

    # Reboots
    - name: Reboot if required on Debian
      reboot:
        msg: "Reboot initiated by Ansible after Debian updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when:
        - ansible_os_family == "Debian"
        - debian_reboot_required.stat.exists

