- name: create itst and sudo group
  ansible.builtin.group:
    name: "sudo"
    state: present

- name: create itst user
  user:
    name: itst
    system: yes
    groups: "sudo"
    create_home: true
    home: "/home/itst"
    shell: "/bin/bash"

- name: Ensure the directory /.ssh exists
  ansible.builtin.file:
    path: /home/itst/.ssh
    state: directory
    owner: itst
    group: itst

- name: create sbin
  ansible.builtin.file:
    path: /home/itst/sbin
    state: directory
    owner: itst
    group: itst

- name: copy sbin scripts
  copy:
    src: files/itst/sbin/pufferpannel.sh
    dest: /home/itst/sbin/pufferpannel.sh
    owner: itst
    group: itst
    mode: 700

- name: copy sbin scripts
  copy:
    src: files/itst/sbin/tor_relay.sh
    dest: /home/itst/sbin/tor_relay.sh
    owner: itst
    group: itst
    mode: 700

- name: copy custom authorized_key file
  copy:
    src: files/itst/authorized_keys
    dest: /home/itst/.ssh/authorized_keys
    owner: itst
    group: itst

- name: copy tmux cnf
  copy:
    src: files/itst/tmux.conf
    dest: /home/itst/.tmux.conf
    owner: itst
    group: itst

- name: copy custom .bashrc file
  copy:
    src: files/itst/bashrc
    dest: /home/itst/.bashrc
    owner: itst
    group: itst

- name: copy custom .bash_prompt file
  copy:
    src: files/itst/bash_prompt
    dest: /home/itst/.bash_prompt
    owner: itst
    group: itst

- name: copy custom bash_aliases file
  copy:
    src: files/itst/bash_aliases
    dest: /home/itst/.bash_aliases
    owner: itst
    group: itst

- name: copy sudoer_itst
  copy:
    src: files/itst/ssh/sudoer_itst
    dest: /etc/sudoers.d/itst
    owner: root
    group: root
    mode: 0440

