---
- name: Install Prometheus
  hosts: pve-3
  become: yes
  gather_facts: no

  vars:
    prometheus_version: "3.0.1"
    prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prometheus_install_dir: "/opt/prometheus"
    prometheus_user: "prometheus"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - wget
          - tar
        state: present

    - name: Create Prometheus user
      user:
        name: "{{ prometheus_user }}"
        shell: /usr/sbin/nologin
        home: "{{ prometheus_install_dir }}"
        state: present

    - name: Download Prometheus binary
      get_url:
        url: "{{ prometheus_download_url }}"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp/"
        remote_src: yes
        extra_opts: [--strip-components=1]

#    - name: Extract Prometheus
#      unarchive:
#        src: "/tmp/prometheus.tar.gz"
#        dest: "/tmp/"
#        remote_src: yes

    - name: List extracted files
      command: ls -l /tmp/

    - name: Move Prometheus binaries to installation directory
      shell: |
        mv /tmp/prometheus/* {{ prometheus_install_dir }}
      args:
        creates: "{{ prometheus_install_dir }}/prometheus"

#    - name: Move Prometheus binaries to installation directory
#      command: >
#        mv /tmp/prometheus-{{ prometheus_version }}/* {{ prometheus_install_dir }}
#      args:
#        creates: "{{ prometheus_install_dir }}/prometheus"

    - name: Set ownership of Prometheus directory
      file:
        path: "{{ prometheus_install_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        recurse: yes

    - name: Create systemd service for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_user }}
          Type=simple
          ExecStart={{ prometheus_install_dir }}/prometheus --config.file={{ prometheus_install_dir }}/prometheus.yml --storage.tsdb.path={{ prometheus_install_dir }}/data

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
