---
- name: set a cron job
  hosts: quest
  become: yes
  gather_facts: no
  tasks:
  
    - name: move the script we want to run
      copy:
        src: files/itst/sbin/disk_alert.sh
        dest: /home/itst/sbin/
        owner: itst
        group: itst
        mode: 0755
      
    - name: set cron job
      cron:
        name: set disk check cron
        user: itst
        minute: "*/10"
        job: /home/itst/sbin/disk_alert.sh

    - name: move script for login alerts
      copy:
        src: files/usr/local/bin/ntfy-ssh-login.sh
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755

    - name: add ntfy to end of pam.d
      lineinfile:
        dest: /etc/pam.d/sshd
        line: "session optional pam_exec.so /usr/local/bin/ntfy-ssh-login.sh"
        state: present
