---
- name: Download and Install all dist updates and reboot if needed
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  
    - name: update repository index and install all updates ubuntu
      apt:
        update_cache: yes
        name: '*'
        state: latest

    - name: install unattended upgrades
      apt:
      name:
        - unattended-upgrades
        - apt-listchanges
     state: present
      
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

