---
- name: Download and Install all dist updates and reboot if needed
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  
    - name: update repository index and install all updates ubuntu
      apt:
        update_cache: yes
        name: '*'
        state: latest
      
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Notify completion by sending a curl request
      command: curl -d "install updates ansible script has ended" http://172-234-150-15.ip.linodeusercontent.com/itst
