---
- name: Download and Install all dist updates and reboot
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update packages on Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update packages on RHEL/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update packages on Alpine
      apk:
        upgrade: yes
      when: ansible_os_family == "Alpine"

    - name: Always reboot after updates
      reboot:
        msg: "Reboot initiated by Ansible after system updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
